#!/bin/bash
#
OIFS=$IFS;
IFS=",";

start(){
  local env_file="config/development/env.sh";

  if [ -f "$env_file" ]; then source "$env_file"; fi

  # $db se obtiene de env_file
  local dbname="$db"
  local host='127.0.0.1:27017'

  local collections=`mongo "$host/$dbname" --eval "rs.slaveOk();db.getCollectionNames();"`;
  local collectionArray=($collections);

  for ((i=0; i<${#collectionArray[@]}; ++i));
  do
      echo 'exporting collection' ${collectionArray[$i]}
      mongoexport --host $host --db $dbname -c ${collectionArray[$i]} --jsonArray --out private/data/${collectionArray[$i]}.json;
      sleep 1
  done
}

start

IFS=$OIFS;
