#!/bin/bash
#

start(){
  local env_file="config/development/env.sh";

  if [ -f "$env_file" ]; then source "$env_file"; fi

  # $db se obtiene de env_file
  local dbname="$db"
  local host='127.0.0.1:27017'

  echo "Dumping database: $dbname"
  mongodump --host $host --db $dbname --out private/data/backup;

}

start
